# Generated by Django 5.0.6 on 2024-05-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0017_remove_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='category',
            field=models.IntegerField(choices=[(1, 'Free 1 Day Pass'), (2, 'Complimentary Personal Training Session'), (3, 'Complimentary Zumba Class'), (4, 'Complimentary Spin Class / Indoor Cycling Class'), (5, 'Complimentary Power Yoga Class'), (6, 'Complimentary Kickboxing Class')], max_length=60),
        ),
    ]
