# Generated by Django 5.0.6 on 2024-05-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0018_alter_enquiry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='ind@gmail.com', max_length=100),
        ),
    ]
