# Generated by Django 5.0.6 on 2024-06-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0021_alter_trainer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile_pic.jpg', null=True, upload_to='profile_pic/MemberProfilePic/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile_pic.jpg', null=True, upload_to='profile_pic/MemberProfilePic/'),
        ),
    ]
